### ISSUE TITLE
Calculation of Cost when extending route

### ISSUE THREAD

**Issue by Jakob-B** [mattianeroni/clarke-wright-savings#1]
First of all: Thank you very much for this amazing library, that really is a "useful algorithm" ;)

Now to the issue: I think the calculation of cost when extending the route does not behave as expected.  The cost of a route are sometimes higher than they should be, some edges seem to be added multiple times.

Looking at the code in detail, I believe the reason for this to be in algorithm.py/extend, where it says:
```
def extend (self, edges):
        """
        This method is preferable for extending the route with new
        edges because it automatically updates the cost too.

        :param edges: The new edges to add to the route.
        """
        self.edges.extend(edges)
        self.cost += sum(edge.cost for edge in self.edges)
```

However, adding to the current route the costs of all the edges belonging to this route is wrong (in my opinion), as `self.cost` already contains the cost of the edges that were already there. Only the cost of the new eges should be added. Therefore, it should be:

```
self.cost += sum(edge.cost for edge in edges)
```
With this change I get the expected behaviour regarding route costs in my test instances.  

I hope I was able to make my point clear. Please let me know if I misunderstood anything and the original code actually behaves as intended.

Thanks again for this useful algorithm!

Jakob

**Comment by mattianeroni** [comment]
Dear Jakob, 

thank you for the interest in my library and for the very helpful note.
I think you are perfectly right! The calculation of the cost into the extend method should be exactly the one you mentioned.

Can you commit the change so that I push it and your contribution to the library can be visible?
I can also make the change, but I would like you to appear as a contributor.

Let me know, otherwise I just make the correction ASAP.
